// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfjwalztrqunydnuehso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmandhbHp0cnF1bnlkbnVlaHNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTkwNjIsImV4cCI6MjA3MTY5NTA2Mn0.Rlr8c8g9ClqYQY4wtunBrX9aW9HhxdHLUgjb1byOCZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});